### ISSUE TITLE
Implement lowering of comparing instructions.

### ISSUE THREAD

**Issue by MCJOHN974** [near/wasmtime#103]
Some of comparing instructions are still not implemented:
- [x] ``i64.ge_s``
- [x] ``i64.ge_u``
- [x] ``i64.gt_s``
- [x] ``i64.gt_u``
- [x] ``i64.le_s``
- [x] ``i64.le_u``
- [x] ``i32.gt_s``
- [x] ``i32.gt_u``
- [x] ``i32.ge_s``
- [x] ``i32.ge_u``
- [x] ``i32.le_s``
- [x] ``i32.le_u``

**Comment by akashin** [comment]
All comparisons should be supported after https://github.com/near/wasmtime/pull/135
