### ISSUE TITLE
Strange line in ``test_summary.csv``

### ISSUE THREAD

**Issue by MCJOHN974** [near/wasmtime#122]
In ``test_summary.csv`` we have ``cranelift/zkasm_data/spectest/i32`` and ``cranelift/zkasm_data/spectest/i32/`` lines with different results. Is it a bug?

**Comment by MCJOHN974** [comment]
@akashin, can you take a look please

**Comment by akashin** [comment]
Yes, this should fix it: https://github.com/near/wasmtime/pull/123
