### ISSUE TITLE
Support different types of asserts in tests.

### ISSUE THREAD

**Issue by MCJOHN974** [near/wasmtime#145]
Currently we have only one assert supported -- ``assert_eq``. While we was working with arithmetics it was enough. But now, when we started work with memory operations, extends, etc, we need reacher set of asserts -- ``assert_fail``, ``assert_trap``, etc.

**Comment by MCJOHN974** [comment]
Since `assert_fail`, `assert_trap` are irrelevant due to migration to filetests is #229 resolving it?

cc @akashin

**Comment by akashin** [comment]
> Since `assert_fail`, `assert_trap` are irrelevant due to migration to filetests is #229 resolving it?
> 
> cc @akashin 

Yes, I think we can mark this as resolved.
