### ISSUE TITLE
Tools to run generated ZK ASM through zkevm-proverjs

### ISSUE THREAD

**Issue by akashin** [near/wasmtime#18]
Some links to check out:
- https://github.com/0xPolygonHermez/zkevm-rom/blob/develop/.github/workflows/main.yaml#L17
- https://github.com/actions/checkout

**Comment by MCJOHN974** [comment]
@akashin was this issue resolved by [this PR](https://github.com/near/wasmtime/pull/7)?

**Comment by akashin** [comment]
> @akashin was this issue resolved by [this PR](https://github.com/near/wasmtime/pull/7)?

Yes, feel free to close it!
