### ISSUE TITLE
Should we use handwritten tests?

### ISSUE THREAD

**Issue by MCJOHN974** [near/wasmtime#189]
Currently, we have tests generated from wasm spectest, and some handwritten ones. Do we really want to keep the second?

Pros:
- without handwritten ones test infrastructure will be simpler
Cons:
- maybe we will need some complicated tests not covered by spectest

**Comment by akashin** [comment]
Given our recent discussions, I think the conclusion is that we want to use handwritten tests and we want to keep them as filetests written in CLIF. @MCJOHN974  Is there anything else to figure out here? If not, let's close this.

**Comment by MCJOHN974** [comment]
Resolved by https://github.com/near/wasmtime/pull/215
