### ISSUE TITLE
How `state.csv` monitoring tool should look like?

### ISSUE THREAD

**Issue by MCJOHN974** [near/wasmtime#191]
Currently, we don't automatically check any changes in `state.csv` made by PR. It can lead to author missed that he broke a test + reviewer missed that PR brokes a test = we commit code which brakes a test to the main branch.

We want to have some tool which will help to prevent such scenario and help reviewer to pay less attention to `state.csv` files during the review.

I suggest to implement it as a github bot, which calculates diff between main and feature branches and writes it to PR discussion.
It don’t block PR merge. It just write some facts into PR discussion, for example:

 human
@bot diff

 bot
test X have ‘pass’ status in main branch and ‘compilation error’ status in feature branch

Than, human read this information and makes a desicion to approve PR or not.
Pros:

- When human make final decision it automatically resolves all corner cases, such as adding\removing test, even corner cases we don’t expect now
-  I think somebody maybe already implemented such bot, and we can reuse it, but don't know any suitable for us implementation.

Cons:
- Human make decision == less automation & human factor. But, if bot write’s diff only in case of quality degradation (‘pass’ => ‘runtime error’ or ‘runtime error’ => ‘compilation error’), it’s output will relatively small. We have 105 closed PR’s now. As I remember, it was 1 or 2 PR’s where we intentionaly commit code which reduce amount of passing tests. Thus, in majority of cases we expect bot output be empty. In very few cases we will still need to do manual review of failed tests, and it is possible that between 100 intentionally failed tests will be 1 unintentionally failed test

**Comment by nagisa** [comment]
GHA workflows can write comments on PRs. Avoids having to set up the entire authentication setup and infrastructure for an external tool.

**Comment by nagisa** [comment]
Some examples of the GHA actions:

https://github.com/marketplace/actions/create-comment
https://github.com/marketplace/actions/comment-pull-request
