### ISSUE TITLE
Should we use cranelift filetests?

### ISSUE THREAD

**Issue by MCJOHN974** [near/wasmtime#192]
# This issue is for discussion of migrating part of our testsuite to cranelift filetests.

## Some prerequisite: 
Here are some questions we asked in previous sync.
Investigate whether wasmtime filetests allow us to:
 - Test wasm features that we care about
 - Test correctness of generated zkasm code
 - See the diff of codegen to spot weird behaviors during code review
 - How expensive is it to adopt this solution?

### Procs:
- Filetests allow to have source code not only in wasm, but also in clif. It can be useful for testing some helper-instructions we make, but wasm don't have

### Cons:
- Cranelift filetests don't supposed to have wasm source code. It is more about testing compilation from clif for isa and other parts of the compiler. For us it mean, that highly likely we will need to have all spectests in clif
- This migration don't looks like very obvious and will take time
- Speaking about building something what will not deviate cranelift design, simply adding wasm into the filetests **will** deviate cranelift design even more. We will need to have clif generated from wasm spectest

### My answers for questions from the meeting:
- Test wasm features that we care about: yes, but will take time to build.
- Test correctness of generated zkasm code: same as above.
- See the diff of codegen to spot weird behaviors during code review: from my understanding only in CI job log, not in changed files.
- How expensive is it to adopt this solution? I think if we want avoid hacks and trully and fully adopt our tests to filetest infra it will take a lot of work:
1) generate clif from wasm spectest
2) add zkasm processor as runner to filetest infra
3) any pitfalls???

And, with this approach, we will lose:
1) diff between generated code in PR review (i think it will terrible to read huuuge CI job log and find diffs). Or we can add this diff, but it will be hacky and deviate cranelift design
2) any wasm files from repository

I'm not looking at simply adding wasm to filetest infra, since it is still hacky and need to be rewrited.

### My suggestions for now
1) keep majority of testing infra outside filetest. We can do much less work and still build something which will ok for us, until we will want to merge our code to bytecode alliance repo.
2) for handwritten tests: if it can be written in wasm -- use our infra. If can't, use filetests.
Also, my suggestions won't work if we are planning merge our code to bytecode alliance in nearest future.

**Comment by MCJOHN974** [comment]
Maybe I forgot some reasons we should use filetests? But in general I think, our own infra can do all tasks we want, and will be much faster to build

**Comment by MCJOHN974** [comment]
@akashin, @nagisa, @mooori, WDYT?

**Comment by nagisa** [comment]
> Cranelift filetests don't supposed to have wasm source code. It is more about testing compilation from clif for isa and other parts of the compiler. For us it mean, that highly likely we will need to have all spectests in clif

Can you elaborate why you think this claim holds true? If you look at `cranelift/filetests/filetests/isa/*/wasm` you can see quite a few tests that generate machine code from input wat already. They are even generated with a script – just like we have one to split up the spectest wast into single modules. So intuitively it would seem quite alright to have wasm-based tests and `filetest` already has the necessary pieces for this.

**Comment by nagisa** [comment]
> until we will want to merge our code to bytecode alliance repo.

My suspicion is that we are not going to pursue this goal approximately ever. At the very best we might provide an externally developed & externally loadable backend. So any of the decisions we make should not be based on the prospects of a merge to upstream.

However we should still make sure we have an easy time integrating *with* upstream, which may or may not mean that it should remain straightforward to merge `upstream/master` *into* our fork.

**Comment by akashin** [comment]
@MCJOHN974 , Given that we decided to use filetests, can we close this?

**Comment by MCJOHN974** [comment]
Closed by https://github.com/near/wasmtime/pull/215
