### ISSUE TITLE
`zkasm_runner::run_zkasm` returns a struct with no public field or method 

### ISSUE THREAD

**Issue by MCJOHN974** [near/wasmtime#239]
As I see `zkasm_runner::ExecutionResult`, which is the result type of `zkasm_runner::run_zkasm` is a struct with no public field or method. Therefore, currently there is no way to somehow extract results. Should we add some public method to extract results?

**Comment by akashin** [comment]
Yes, I've made some fields public in https://github.com/near/wasmtime/pull/231, would these be enough?

**Comment by MCJOHN974** [comment]
> Yes, I've made some fields public in #231, would these be enough?

At least for the testing infra it should be enought
