### ISSUE TITLE
Compile in CI.

### ISSUE THREAD

**Issue by MCJOHN974** [near/wasmtime#29]
Currently we check in CI ``.zkasm`` files which are commited, and they can be unrelated to current state of compiler, I think it is better to recompile all test file and test recompiled ``.zkasm`` in each CI run

**Comment by MCJOHN974** [comment]
@akashin @nagisa WDYT, do we need this?

**Comment by akashin** [comment]
[This test](https://github.com/near/wasmtime/blob/main/cranelift/filetests/src/test_zkasm.rs) verifies that the `.zkasm` files in the repository are generated by the current version of the code. If we can ensure that it runs as a part of the CI, we can guarantee that committed files are up to date. Would this resolve the issue of testing the latest files?

**Comment by MCJOHN974** [comment]
Yes, it resolve the issue, thanks
