### ISSUE TITLE
Compiler don't produce a file

### ISSUE THREAD

**Issue by MCJOHN974** [near/wasmtime#36]
I'm running ``$ cargo run --features=all-arch -p cranelift-tools --bin=clif-util wasm --target=sparc ./cranelift/zkasm_data/add.wat`` from ``wasmtime`` repository (last commit of our main branch) and expecting it will generate ``./cranelift/zkasm_data/generated/add.zkasm``, but it don't do that. Also, it don't print anything to stdout and exit with code 0. So I have 2 questions:

1) What actually do this command?
2) How should I compile ``.wat`` to ``.zkasm``?

**Comment by akashin** [comment]
> @nagisa @akashin maybe you can help?

This command is no longer working as I've migrated the `wasm` command fully to the `test_zkasm.rs`: https://github.com/near/wasmtime/pull/9

Now, the way to do .wat -> .zkasm conversion is to add the .wat file to `zkasm_data` and to the `test_zkasm.rs` and re-run the test.
Does this work or do you want a dedicated tool for this conversion?

It should be easy to build a runnable binary for this by factoring out the relevant code from `test_zkasm.rs` into a library.

**Comment by MCJOHN974** [comment]
Yes, that helps, thanks!
