### ISSUE TITLE
Migrate usage documentation

### ISSUE THREAD

**Issue by MCJOHN974** [near/wasmtime#37]

**Comment by MCJOHN974** [comment]
@akashin, I want help with this task (if you didn't started yet)

**Comment by akashin** [comment]
> @akashin, I want help with this task (if you didn't started yet)

No, I did not.
The pages I had in mind are:
- https://hackmd.io/xlfXSX0qQGe2npk4S0Kf3A - probably only a very small portion is relevant now, we should rewrite it to use the script that you've built
- https://hackmd.io/1nhEpfzVTqCmEGOLB8z6LA - could be just an inline link to hackmd document, I don't think we need all of it at the moment
