### ISSUE TITLE
zkasm: decide on strategy for shorter bit-width integers and see what's necessary to implement it

### ISSUE THREAD

**Issue by nagisa** [near/wasmtime#62]
During a call yesterday we’ve talked about what it would take to support integers of bitwidths that aren’t equal to a limb. In particular we saw two distinct cases – 64 bit integers which are larger than a limb, and then 16 or 8-bit integers that are smaller.

Some ideas that we have are:

* Mask out the unnecessary bits as necessary using `AND` (supposedly not particularly efficient);
* The more efficient way is to use operations like `ADD, JMPC` according to the polygon folks. However for short bitwidths getting the carry flag set is not a trivial problem. We came up with a solution where we could actually place the numbers we want to operate on within the high order bits of the register(s), and then perhaps have instructions or methods to move data to-and-from those bits. Basically (for a 32-bit field) `a + b = (a * 2^32 + b * 2^32) / 2^32`. And as long as all operations are executed with values within these high bits, we’d get the expected flag setting behaviour and furthermore we would have a consistent implementation strategies between all sorts of bit-widths.

**Comment by MCJOHN974** [comment]
I have some notes about second approach.
1) wasm have only two integer types -- i32 and i64. When zk-processor will be 64-bit, we can expect that everything for 64 bit will be work as is, without anything extra from our side. wasm don't have i16, i8, etc, so, we need to care only about 32-bit integers.
2) I don't very understand why we need ``JMPC``, I think overflow will work properly without it??? (``0xFFFF_0000 + 0x0002_0000 = 0x0001_0000``
3) In case we using multiplication by ``2 ** 32`` such opcodes as ``sub``, ``add``, ``gt``, ``lt``, ``le``, ``ge``, ``eq``, ``neq``, will work very naturally.
4) zkAsm don't have such bit operations as ``clz``, ``ctz``, ``popcnt`` and in any case we should somehow manually implement it, so one or another approach won't produce extra difficulties.
5) ``mul`` opcode. This is quite interesting. We want something like ``0x0001_0000 * 0x0002_0000 = 0x0002_0000`` which is not true. So here we will need firstly divide one number by ``2 ** 32``, than multiply numbers and it should work.
6) ``div`` opcode. +- same as multiplication. We just divide one to another, than multiply result by ``2 ** 32`` and everything will work, even rounding will be correct.
7) ``rot* sh*`` will corrupt our 32 trailing zero, so we will need to mask them. But since zkasm don't have this opcodes, and we will implement them manually, I think one extra ``AND`` will not be relatively large overhead.
8) ``rem`` sounds like a tricky opcode and here we can only divide both numbers by ``2 ** 32``, calculate rem and than multiply by ``2 ** 32`` back. Maybe here some more hacks are possible, think here we need a bit more understanding on what should be checked by ``ARITH`` (already in zkasm sync agenda)
9) operating with environment variables (``local\global.set\get\tie``) maybe we need something? Maybe we should each time storing here divide by ``2 ** 32`` and any time loading multiply?
10) Maybe it will be some difficulties with formal proof of compiler correctness???? but I'm not familiar with it at all.

Summary:

Operating with numbers multiplied by ``2 ** 32`` will work mostly without any extra effort, sometimes some extra operation added to operations, which are already heavy

**Comment by MCJOHN974** [comment]
First approach:

1) Naive way: make ``AND`` masking after each operation.
2) I think we can make something like this:
```
C :OPCODE // here we assume opcode have A and B as inputs.
end_op :JMPNC
// mask A and B
C :OPCODE
end_op
```
And here, we will do extra computation only when overflow occurs. And for any operation, including ``mul``, ``div``, ``rem`` we will not have any extra computation until overflow occurs.
2.1) In that case, we will need masking before each comparing operation 
2.2) ``rot*, sh*`` need mask before operation for ``rot``
2.3) no problems with ``global\local.set\get``? Or maybe need to mask before ``local\global.set``????

**Comment by MCJOHN974** [comment]
Mask vs ``* 2**32``

Mask cons:
1) 2 extra ``AND`` before each comparing except ``eq``, ``neq``.
2) 2 extra ``AND`` and duplicate operation in case of 64-bit overflow
3) 1 extra ``AND`` before ``rot``

Multiplication by ``2 ** 32`` cons:
1) extra multiplications and divisions in ``mul``, ``rem``, ``div``. As I understand shouldn't be done in whole in env and it will produce ~5 extra opcodes for ``mul`` and ``div`` and +-15 for ``rem``
2) ``rot*``, ``sh*`` will produce 1 extra ``AND`` each.

Don't very understand what to do with ``local\global.set\get`` in both cases, but think in both cases overhead +- same.

So, in total, we have x3 more opcodes in comparsions vs x2 more opcodes in ``div``\``mul`` and x4 in ``rem``

**Comment by nagisa** [comment]
> wasm have only two integer types -- i32 and i64. When zk-processor will be 64-bit, we can expect that everything for 64 bit will be work as is, without anything extra from our side. wasm don't have i16, i8, etc, so, we need to care only about 32-bit integers.

Fair. There's still risk that cranelift will generate operations with smaller bit-widths but that probably isn’t a huge deal;

> I don't very understand why we need JMPC, I think overflow will work properly without it???

I believe there was some confusion about what was meant by "overflow" during the discussion. To clarify: what you’re interpreting is implicit handling of overflow via a wrap-around. People from Polygon where talking about how to *detect* whether an overflow condition has occurred, which allows for arbitrary handling of overflow. For wasm in particular that matters because some of the instructions prescribe a different way of handling overflow (e.g. saturation – a number is kept at the maximum or minimum value) and not wrap-around.

> operating with environment variables (local\global.set\get\tie) maybe we need something? Maybe we should each time storing here divide by 2 ** 32 and any time loading multiply?

`local`s can contain the scaled numbers no problem, they are not observable externally in any way. `global`s are a bit more tricky as they can be imported, so at least for those scaling will need to be undone. I’m not sure if cranelift makes it easy to see if a global is imported or not, but initially we could take a conservative approach.

> Maybe it will be some difficulties with formal proof of compiler correctness???? but I'm not familiar with it at all.

I’ve doubts we’ll be formally proving what’s effectively an MVP project. This kind of work unfortunately requires care and foresight from the very beginning, and would otherwise be a large research undertaking, as none of us are familiar with how to approach this kind of a problem statement.

> So, in total, we have x3 more opcodes in comparsions vs x2 more opcodes in div``muland x4 inrem``

Polygon folks claim that binary logical operations are comparatively very expensive in wall-clock time, which is ultimately the kind of performance characteristic that we care about, I believe. If we execute a boatload of masking operations, I can imagine that our execution throughput would tank quite significantly. On the other hand my intuition is that multiplying and dividing by 2**32 in polynomial fields should be pretty trivial all things considered.

**Comment by nagisa** [comment]
> zkAsm don't have such bit operations as clz, ctz, popcnt and in any case we should somehow manually implement it, so one or another approach won't produce extra difficulties.

There are well-known equivalences for these operations. `clz` in particular interestingly in zkasm would probably be most efficiently implemented as `floor(log2(number))`. I’m not sure if there’s panything that’s more efficient than this for `popcnt`](https://godbolt.org/z/EzYfoqon3).

**Comment by MCJOHN974** [comment]
Thanks for clarifications, @nagisa.

> Polygon folks claimed that binary logical operations are comparatively very expensive in wall-clock time, which is ultimately the kind of performance characteristic that we care about, I believe. If we execute a boatload of masking operations, I can imagine that our execution throughput would tank quite significantly. On the other hand my intuition is that multiplying and dividing by 2**32 in polynomial fields should be pretty trivial all things considered.

So, we can start with implementing smaller integers via multiplying them by ``2 ** 32`` I think.

**Comment by akashin** [comment]
> Mask vs `* 2**32`
> 
> Mask cons:
> 
>     1. 2 extra `AND` before each comparing except `eq`, `neq`.
> 
>     2. 2 extra `AND` and duplicate operation in case of 64-bit overflow
> 
>     3. 1 extra `AND` before `rot`
> 
> 
> Multiplication by `2 ** 32` cons:
> 
>     1. extra multiplications and divisions in `mul`, `rem`, `div`. As I understand shouldn't be done in whole in env and it will produce ~5 extra opcodes for `mul` and `div` and +-15 for `rem`
> 
>     2. `rot*`, `sh*` will produce 1 extra `AND` each.
> 
> 
> Don't very understand what to do with `local\global.set\get` in both cases, but think in both cases overhead +- same.
> 
> So, in total, we have x3 more opcodes in comparsions vs x2 more opcodes in `div`/`mul` and x4 in `rem`

Did we take into account that Arithmetic ops (multiplications) are [twice as expensive](https://github.com/0xPolygonHermez/zkevm-rom/blob/c17c1664a654e27de67bcbcbe6b6ae44c5b93274/main/constants.zkasm#L77C1-L77C1) as Binary ops (Binary op is 4 clocks and Arithmetic op is 8 clocks)?

**Comment by MCJOHN974** [comment]
> Did we take into account that Arithmetic ops (multiplications) are [twice as expensive](https://github.com/0xPolygonHermez/zkevm-rom/blob/c17c1664a654e27de67bcbcbe6b6ae44c5b93274/main/constants.zkasm#L77C1-L77C1) as Binary ops (Binary op is 4 clocks and Arithmetic op is 8 clocks)?

I believe comparsions are much more frequent than multiplication\division. Didn't find exact data, but find a tool which can measure instructions frequency https://docs.oracle.com/cd/E19205-01/820-5372/ahoas/index.html

**Comment by nagisa** [comment]
The instruction frequency tool is not particularly useful since it is meant to work with native binaries. Fortunately for us our CPU is in software and we can instrument it arbitrarily, and so counting instructions or their types should be a fairly trivial addition.

**Comment by MCJOHN974** [comment]
With instructions weight provided by Andrei we have next setup now:

Bitmask:
- Addition: 4 -> 8
- Multiplication: 8 -> 12
- Division: 8 -> 8
- Remainder: 8 -> 8
- Subtract: 4 -> 8
- SHL/SHR: ? -> ? + 4
- Rotation: ? -> ? + 4


multiply by 2**32:
- Addition: 4 -> 4
- Subtract: 4 -> 4
- Multiplication: 8 -> 16
- Division: 8 -> 16
- Remainder: 8 -> 24
- Equality: 4 -> 12

And this: "- Equality: 4 -> 12" sounds like we should use mask instead. @nagisa WDYT?

**Comment by nagisa** [comment]
Entirely up to you all. My current feeling that for any semblance of throughput it will be necessary to add additional specialized instructions to zkasm anyway, so any focus on performance right now is kinda a wasted effort. We should get something working first, changing the approach is probably not going to be all that onerous.

**Comment by akashin** [comment]
I believe the initial design and implementation are done here, we can track the follow-up work in https://github.com/near/wasmtime/issues/106
