### ISSUE TITLE
Is it a time to switch to 64-bit zk-processor now?

### ISSUE THREAD

**Issue by MCJOHN974** [near/wasmtime#72]
Recently I runned all our tests with 64-bit zk processor (zkevm-proverjs/feature/64bit). All except one passes, one failed due to a bug in the prover. So, maybe it is a time to start using 64-bit prover?

From my point of view
Proc of switching to 64-bit machine now
1) we will be able to work with implementing correct overflow
2) with 64-bit zkasm we will able to implement everything end-to-end, fully, with all corner cases, instead of implementing base logic now and work with corner cases later.

Cons:
1) 64-bit prover have some bugs now. It will block working on some opcodes, but amount of unblocked work is bigger in my opinion.
2) maybe bug in prover will lead to zkasm which should fail won't fail, and it will allow bugs in our code pass the tests, but is think probability of such scenario is small enough.

I think, if I don't missing some significant cons of this switch, now is good time to do it.

**Comment by MCJOHN974** [comment]
upd: bug which was leading to failing of one of our tests fixed already. Now all our tests passes with 64-bit prover

**Comment by akhi3030** [comment]
Sounds like we should move to the 64 bit processor then?
