### ISSUE TITLE
What ``cranelift::filetest::test_zkasm::optimize_labels`` do?

### ISSUE THREAD

**Issue by MCJOHN974** [near/wasmtime#96]
Specially this line looks strange for me:
```
let pos_end = pos + line[pos..].find(&")").unwrap();
```
(cranelift/filetests/src/test_zkasm.rs, line 88).

Which label naming policy we have? How labels should be named?

**Comment by MCJOHN974** [comment]
@akashin, maybe you can help?

**Comment by akashin** [comment]
> @akashin, maybe you can help?

Does https://github.com/near/wasmtime/pull/97 clarify this?

For the names of the labels, we must ensure they are unique across multiple Cranelift functions and are valid ZK ASM labels, but otherwise, we are free to choose anything.

**Comment by MCJOHN974** [comment]
Fixed at #97
